import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	sidebar: [
		{
			type: 'category',
			label: 'General',
			items: ['General/Welcome', 'General/tech', 'General/civic', 'General/cv'],
			collapsed: false
		}
		// {
		// 	type: 'category',
		// 	label: 'Build Logs',
		// 	collapsed: false,
		// 	items: [
		// 		{
		// 			type: 'autogenerated',
		// 			dirName: 'BuildLog'
		// 		}
		// 	]
		// }
	]
};

export default sidebars;
