import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
	sidebar: [
		{
			type: 'category',
			label: 'General',
			collapsed: false,
			items: [
				{
					type: 'autogenerated',
					dirName: 'General'
				}
			]
		}
	]
};

export default sidebars;
